apiVersion: batch/v1
kind: CronJob
metadata:
  name: znv2ef-job
  namespace: uvasds-services
spec:
  schedule: "0-59/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: znv2ef-job-container
            image: ghcr.io/sierralplatt/testcontainer:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: ds2002-mongo
            resources:  
              limits:   
                cpu: "0.25"
                memory: 512Mi
              requests: 
                cpu: "0.1"
                memory: 256Mi
          restartPolicy: Never
      ttlSecondsAfterFinished: 86400